{"Launchpad":"https://bugs.launchpad.net/bugs/1191960","Id":"1191960","Gerrit":"https://review.openstack.org/47632","IdGerrit":"47632","IdCommit":"de257d1a2b91e8060ff3532ced25cb2a67b14267","Files":["cinder/brick/local_dev/lvm.py","cinder/volume/drivers/lvm.py","etc/cinder/rootwrap.d/volume.filters"],"Lines_Inseted":29,"Lines_Deleted":5,"CommitParent":"93fb1ac66fae8d22f91d46e327f32dda671548f5","Classification":"Bug","KeywordsTitle":"force-delete of volume errors ","Description":"consequence of bug, error, anomalies","KeywordsCommit":"fix issue","Comments":""}