{"Launchpad":"https://bugs.launchpad.net/bugs/1279764","Id":"1279764","Gerrit":"https://review.openstack.org/81176","IdGerrit":"81176","Files":["cinder/api/contrib/admin_actions.py","cinder/api/contrib/backups.py","cinder/backup/api.py","cinder/tests/api/contrib/test_admin_actions.py","cinder/tests/policy.json"],"Lines_Inseted":25,"Lines_Deleted":4,"CommitParent":"fed5843972ced19d0c04d99a3b100a6108152063","Classification":"Bug","KeywordsTitle":"no reset","Description":"stuck in creating, cannot be deleted, none for backups, error","KeywordsCommit":"added, can delete, error state, struck, can't remove/delete, not available, forced Removal of backup(s), explicitly update, error, available, error_deleting","Comments":""}