{"Launchpad":"https://bugs.launchpad.net/bugs/1368527","Id":"1368527","Gerrit":"https://review.openstack.org/129613","IdGerrit":"129613","IdCommit":"3821206ff1455ffc682739911f7f59bdde6e18d2","Files":["cinder/openstack/common/strutils.py"],"Lines_Inseted":6,"Lines_Deleted":1,"CommitParent":"3449e05578a859d855e1743131f723249189dfdc","Classification":"Bug","KeywordsTitle":"failed","Description":"problem, error, exeption","KeywordsCommit":"fix a delete volume failure","Comments":""}