{"Launchpad":"https://bugs.launchpad.net/bugs/1410566","Id":"1410566","Gerrit":"https://review.openstack.org/175349","IdGerrit":"175349","IdCommit":"89a6082d089facb79a7c74d6a0d8c3853d9046f9","Files":["cinder/brick/iscsi/iscsi.py","cinder/tests/test_iscsi.py","cinder/volume/iscsi.py"],"Lines_Inseted":15,"Lines_Deleted":3,"CommitParent":"48c792513fd342a5f82122b12e4ed2afd0de2ae7","Classification":"Bug","KeywordsTitle":"fail to delete","Description":"fails, ProcessExecutionError, NotFound exception","KeywordsCommit":"overwrite existing credentials, inaccessible volume","Comments":""}