{"Launchpad":"https://bugs.launchpad.net/bugs/1425100","Id":"1425100","Gerrit":"https://review.openstack.org/158713","IdGerrit":"158713","IdCommit":"667c1dc511f40854a8bc5ce62ea1461735ba8fc2","Files":["cinder/tests/unit/test_smbfs.py","cinder/tests/unit/windows/test_smbfs.py","cinder/volume/drivers/smbfs.py","cinder/volume/drivers/windows/smbfs.py"],"Lines_Inseted":98,"Lines_Deleted":26,"CommitParent":"9ba2d75a5af665f14549787c88a79e30283304f4","Classification":"Bug","KeywordsTitle":"fail to retrieve","Description":"can also fail in certain environments, avoid this","KeywordsCommit":"fix, retrieving","Comments":""}