{"Launchpad":"https://bugs.launchpad.net/bugs/1441050","Id":"1441050","Gerrit":"https://review.openstack.org/171482","IdGerrit":"171482","IdCommit":"ff50c28386e27654688a7ef255f70f2fc3bcde37","Files":["cinder/volume/drivers/glusterfs.py"],"Lines_Inseted":1,"Lines_Deleted":1,"CommitParent":"1c06834e8c0c7f4a55103cdcc08744e52f0d234d","Classification":"Bug","KeywordsTitle":"test failure ","Description":"testcase fails, failing, failures, bug","KeywordsCommit":"returning, returns","Comments":"This is a Partial-Bug."}