{"Launchpad":"https://bugs.launchpad.net/bugs/1444855","Id":"1444855","Gerrit":"https://review.openstack.org/175475","IdGerrit":"175475","IdCommit":"877c8e7d8c0d397021e1a06b2d2a36962d6a9d42","Files":["cinder/volume/drivers/rbd.py"],"Lines_Inseted":2,"Lines_Deleted":0,"Classification":"Bug","KeywordsTitle":"doesn't support","Description":"fails to connect, results error, error, ObjectNotFound: error calling connect","KeywordsCommit":"add missing name support","Comments":""}
