{"Launchpad":"https://bugs.launchpad.net/bugs/1454835","Id":"1454835","Gerrit":"https://review.openstack.org/183498","IdGerrit":"183498","IdCommit":"7955d5fc66340f826255ac81a3984d7984f56041","Files":["cinder/tests/test_volume.py","cinder/volume/drivers/lvm.py"],"Lines_Inseted":4,"Lines_Deleted":2,"CommitParent":"0466eed8341c3485232f1b7d150bbb3beb4666bb","Classification":"Bug","KeywordsTitle":"destroys volume data","Description":"volume data was broken, corrupted,","KeywordsCommit":"does not pass volume size, corrupted, fixed","Comments":""}