{"Launchpad":"https://bugs.launchpad.net/bugs/1497413","Id":"1497413","Gerrit":"https://review.openstack.org/237755","IdGerrit":"237755","IdCommit":"4bbf59cd06cd92031525c738e83c67823a882ff2","Files":["cinder/tests/unit/volume/drivers/emc/scaleio/test_misc.py","cinder/volume/drivers/emc/scaleio.py"],"Lines_Inseted":13,"Lines_Deleted":2,"CommitParent":"ccbe5340278434ffb3b6072ff1eec1a5e79800b7","Classification":"Bug","KeywordsTitle":"fails, no confgured","Description":"AttributeError","KeywordsCommit":"checks","Comments":""}