{"Launchpad":"https://bugs.launchpad.net/bugs/1500583","Id":"1500583","Gerrit":"https://review.openstack.org/235282","IdGerrit":"235282","IdCommit":"61026d4e4f2a58dd84ffb2e4e40ab99860b9316a","Files":["cinder/locale/cinder-log-error.pot","cinder/locale/cinder-log-info.pot","cinder/locale/cinder-log-warning.pot","cinder/locale/cinder.pot","cinder/locale/tr_TR/LC_MESSAGES/cinder.po","cinder/tests/unit/test_emc_vmax.py","cinder/tests/unit/test_huawei_drivers.py","cinder/tests/unit/volume/drivers/netapp/dataontap/client/test_api.py","cinder/volume/drivers/emc/emc_vmax_common.py","cinder/volume/drivers/netapp/dataontap/client/api.py"],"Lines_Inseted":1,"Lines_Deleted":1169,"CommitParent":"b22c3d695beb375aca99f28941c0a19d66815b26","Classification":"Unknown","KeywordsTitle":"doesn't actually delete","Description":"driver fails to locate, fails to delete","KeywordsCommit":"It contains no actual changes to the master branch","Comments":"description not clear in defining if it is a bug or not..."}