{"Launchpad":"https://bugs.launchpad.net/bugs/1504735","Id":"1504735","Gerrit":"https://review.openstack.org/233828","IdGerrit":"233828","IdCommit":"d45adaf08cce818f5c082fab467bd730052abaa1","Files":["cinder/volume/driver.py","cinder/volume/drivers/lvm.py","cinder/volume/flows/manager/create_volume.py","cinder/volume/manager.py"],"Lines_Inseted":11,"Lines_Deleted":11,"CommitParent":"867fccf833ffc597aa986cb6ff1b3b5c1101b9ba","Classification":"Bug","KeywordsTitle":"no need to use  exception","Description":"exception, no exception handler is used, no need to use, error, may result in the failure, bug","KeywordsCommit":"only use, this can cause error","Comments":""}