{"Launchpad":"https://bugs.launchpad.net/bugs/1506212","Id":"1506212","Gerrit":"https://review.openstack.org/236037","IdGerrit":"236037","IdCommit":"f410bfb76a60e83e16ced20be6d4b3351de191d7","Files":["cinder/tests/unit/volume/drivers/netapp/eseries/fakes.py","cinder/tests/unit/volume/drivers/netapp/eseries/test_client.py","cinder/tests/unit/volume/drivers/netapp/eseries/test_library.py","cinder/volume/drivers/netapp/eseries/client.py","cinder/volume/drivers/netapp/eseries/library.py"],"Lines_Inseted":96,"Lines_Deleted":36,"CommitParent":"170aac0ab03cc2626db0746fdc6a39fa2e775913","Classification":"Bug","KeywordsTitle":"inadvertent deletion","Description":"delete, inaccurately report, misreport, no longer exists","KeywordsCommit":"fix issue, updates, use the correct method","Comments":""}