{"Launchpad":"https://bugs.launchpad.net/bugs/1518050","Id":"1518050","Gerrit":"https://review.openstack.org/247769","IdGerrit":"247769","IdCommit":"e151aecab2dfd1ff37a01e38e1232a170bd5a13b","Files":["cinder/volume/flows/manager/manage_existing.py"],"Lines_Inseted":2,"Lines_Deleted":2,"CommitParent":"ae84ce085feaf9d021412c08ecd7d6a0a99d1e0f","Classification":"Bug","KeywordsTitle":"TypeError","Description":"error, FAILURE, ","KeywordsCommit":"fail","Comments":""}
